/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Funcionarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcinho
 */
public class BuscarFuncionario extends javax.swing.JFrame {

    Funcionarios f;
    //RepositorioFuncionarios fdata;
    

    /**
     * Creates new form BuscarFuncionario
     */
    public BuscarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtregistro = new javax.swing.JTextField();
        jtmatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtdataCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtRG = new javax.swing.JTextField();
        jbvoltar = new javax.swing.JButton();
        jtnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtbairro = new javax.swing.JTextField();
        jbsalvar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtendereco = new javax.swing.JTextField();
        jtcidade = new javax.swing.JTextField();
        jcsexo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcUF = new javax.swing.JComboBox();
        jcsetor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jtCEP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtusuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jpsenha = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jpconfSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jtcontato = new javax.swing.JTextField();
        jbpesquisar = new javax.swing.JButton();
        jbeditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("N° CPF");

        jtCPF.setEditable(false);
        jtCPF.setEnabled(false);

        jLabel1.setText("Registro");

        jLabel12.setText("Matrícula do Funcionário");

        jtregistro.setEditable(false);
        jtregistro.setEnabled(false);

        jLabel2.setText("Data Cadastro");

        jLabel13.setText("N° RG");

        jtdataCadastro.setEditable(false);
        jtdataCadastro.setEnabled(false);

        jLabel4.setText("Endereço");

        jtRG.setEditable(false);
        jtRG.setEnabled(false);

        jbvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon voltar.png"))); // NOI18N
        jbvoltar.setText("Voltar");
        jbvoltar.setBorder(null);
        jbvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvoltarActionPerformed(evt);
            }
        });

        jtnome.setEditable(false);
        jtnome.setEnabled(false);

        jLabel5.setText("Bairro");

        jtbairro.setEditable(false);
        jtbairro.setEnabled(false);

        jbsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon salvar.png"))); // NOI18N
        jbsalvar.setText("Salvar");
        jbsalvar.setBorder(null);
        jbsalvar.setEnabled(false);
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon cancelar.png"))); // NOI18N
        jbcancelar.setText("Cancelar");
        jbcancelar.setBorder(null);
        jbcancelar.setEnabled(false);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Completo");

        jLabel14.setText("Sexo");

        jLabel6.setText("Cidade");

        jtendereco.setEditable(false);
        jtendereco.setEnabled(false);

        jtcidade.setEditable(false);
        jtcidade.setEnabled(false);

        jcsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Masculino", "Feminino" }));
        jcsexo.setEnabled(false);

        jLabel7.setText("UF");

        jLabel15.setText("Setor");

        jcUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "PE", "RJ", "RS", "SP" }));
        jcUF.setEnabled(false);

        jcsetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "  Vendas", "  Estoque", "  Financeiro", "  Administrativo", "  Gerencial", " ", " ", " " }));
        jcsetor.setEnabled(false);

        jLabel8.setText("CEP");

        jtCEP.setEditable(false);
        jtCEP.setEnabled(false);

        jLabel9.setText("Email");

        jtemail.setEditable(false);
        jtemail.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login de Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel16.setText("Usuário");

        jtusuario.setEditable(false);
        jtusuario.setEnabled(false);

        jLabel17.setText("Senha");

        jpsenha.setEditable(false);
        jpsenha.setEnabled(false);
        jpsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsenhaActionPerformed(evt);
            }
        });

        jLabel18.setText("Confirma Senha");

        jpconfSenha.setEditable(false);
        jpconfSenha.setEnabled(false);
        jpconfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpconfSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jpsenha)
                    .addComponent(jpconfSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(6, 6, 6)
                .addComponent(jtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpconfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jLabel10.setText("Contato");

        jtcontato.setEditable(false);
        jtcontato.setEnabled(false);

        jbpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon Pesquisar.png"))); // NOI18N
        jbpesquisar.setText("Pesquisar");
        jbpesquisar.setBorder(null);
        jbpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpesquisarActionPerformed(evt);
            }
        });

        jbeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon add.png"))); // NOI18N
        jbeditar.setText("Editar");
        jbeditar.setBorder(null);
        jbeditar.setEnabled(false);
        jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtdataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jbeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(485, 485, 485)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(180, 180, 180)
                                .addComponent(jLabel6)
                                .addGap(288, 288, 288)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(290, 290, 290)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jcsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel15))
                                    .addComponent(jcsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtdataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)
                        .addComponent(jcsetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(jtcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(jtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvoltarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbvoltarActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed
        /*try {
         if (validarCampos()) {
         if (preencherObject()) {
         //salvar no banco
         int returno = fdata.inserir(f);
         if (returno == 0) {
         JOptionPane.showConfirmDialog(this, "Registro salvo com sucesso !");
         limparCampos();
         jtregistro.setEditable(false);
         jtregistro.setEnabled(false);
         jtdataCadastro.setEditable(false);
         jtdataCadastro.setEnabled(false);
         jtmatricula.setEditable(false);
         jtmatricula.setEnabled(false);
         jtnome.setEditable(false);
         jtnome.setEnabled(false);
         jcsexo.setEnabled(false);
         jcsetor.setEnabled(false);
         jtendereco.setEnabled(false);
         jtendereco.setEnabled(false);
         jcUF.setEnabled(false);
         jtbairro.setEditable(false);
         jtbairro.setEnabled(false);
         jtcidade.setEditable(false);
         jtcidade.setEnabled(false);
         jtCEP.setEditable(false);
         jtCEP.setEnabled(false);
         jtemail.setEditable(false);
         jtemail.setEnabled(false);
         jtCPF.setEditable(false);
         jtCPF.setEnabled(false);
         jtcontato.setEditable(false);
         jtcontato.setEnabled(false);
         jtRG.setEditable(false);
         jtRG.setEnabled(false);
         jtusuario.setEditable(false);
         jtusuario.setEnabled(false);
         jpsenha.setEditable(false);
         jpsenha.setEnabled(false);
         jpconfSenha.setEditable(false);
         jpconfSenha.setEnabled(false);
         jbnovo.setEnabled(true);
         jbsalvar.setEnabled(false);
         jbcancelar.setEnabled(false);
        jbvoltar.setEnabled(true);
         } else {
         if (returno == -1) {
         JOptionPane.showMessageDialog(this, "Codigo Já Cadastrado!");
         } else {
         JOptionPane.showMessageDialog(this, "Não possivel inserir o registro !");
         }
         }
         }
         }
         } catch (Exception erro) {
         JOptionPane.showMessageDialog(this, "Erro: "
         + erro.getMessage());

         }  */
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        limparCampos();
        jtregistro.setEditable(false);
        jtregistro.setEnabled(false);
        jtdataCadastro.setEditable(false);
        jtdataCadastro.setEnabled(false);
        jtmatricula.setEditable(false);
        jtmatricula.setEnabled(false);
        jtnome.setEditable(false);
        jtnome.setEnabled(false);
        jcsexo.setEnabled(false);
        jcsetor.setEnabled(false);
        jtendereco.setEnabled(false);
        jtendereco.setEnabled(false);
        jcUF.setEnabled(false);
        jtbairro.setEditable(false);
        jtbairro.setEnabled(false);
        jtcidade.setEditable(false);
        jtcidade.setEnabled(false);
        jtCEP.setEditable(false);
        jtCEP.setEnabled(false);
        jtemail.setEditable(false);
        jtemail.setEnabled(false);
        jtCPF.setEditable(false);
        jtCPF.setEnabled(false);
        jtcontato.setEditable(false);
        jtcontato.setEnabled(false);
        jtRG.setEditable(false);
        jtRG.setEnabled(false);
        jtusuario.setEditable(false);
        jtusuario.setEnabled(false);
        jpsenha.setEditable(false);
        jpsenha.setEnabled(false);
        jpconfSenha.setEditable(false);
        jpconfSenha.setEnabled(false);
        jbeditar.setEnabled(true);
        jbsalvar.setEnabled(false);
        jbcancelar.setEnabled(false);
        jbvoltar.setEnabled(true);
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jpsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsenhaActionPerformed

    private void jpconfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpconfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpconfSenhaActionPerformed

    private void jbpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpesquisarActionPerformed
        /*if (jtmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o código do produto!");
            jtmatricula.requestFocus();
        } else {
            
            f = fdata.buscar(jtmatricula.getText());
            if (f == null) {
                JOptionPane.showMessageDialog(this, "Registro não encontrado!");
            } else {
                jtdataCadastro.setText(f.getDataCadastro());
                jtmatricula.setText(f.getMatricula());
                jtnome.setText(f.getNome());
                jcsexo.setSelectedIndex(f.getSexo());
                jcsetor.setSelectedIndex(f.getSetor());
                jtendereco.setText(f.getEndereco());
                jcUF.setSelectedIndex(f.getUF());
                jtbairro.setText(f.getBairro());
                jtcidade.setText(f.getCidade());
                jtCEP.setText(f.getCEP());
                jtemail.setText(f.getEmail());
                jtCPF.setText(f.getCPF());
                jtcontato.setText(f.getContato());
                jtRG.setText(f.getRG());
                jtusuario.setText(f.getLogin());
                jpsenha.setText(f.getSenha());
                jpconfSenha.setText(f.getConfSenha());
                jbeditar.setEnabled(true);
                jbsalvar.setEnabled(true);
                jbcancelar.setEnabled(true);
                jbvoltar.setEnabled(true);

            }
        }  */
    }//GEN-LAST:event_jbpesquisarActionPerformed

    private void jbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarActionPerformed
        jtregistro.setEditable(false);
        jtregistro.setEnabled(true);
        jtdataCadastro.setEditable(false);
        jtdataCadastro.setEnabled(true);
        jtmatricula.setEditable(false);
        jtmatricula.setEnabled(false);
        jtnome.setEditable(false);
        jtnome.setEnabled(false);
        jcsexo.setEnabled(false);
        jcsetor.setEnabled(false);
        jtendereco.setEnabled(false);
        jtendereco.setEnabled(false);
        jcUF.setEnabled(false);
        jtbairro.setEditable(false);
        jtbairro.setEnabled(false);
        jtcidade.setEditable(false);
        jtcidade.setEnabled(false);
        jtCEP.setEditable(false);
        jtCEP.setEnabled(false);
        jtemail.setEditable(false);
        jtemail.setEnabled(false);
        jtCPF.setEditable(false);
        jtCPF.setEnabled(false);
        jtcontato.setEditable(false);
        jtcontato.setEnabled(false);
        jtRG.setEditable(false);
        jtRG.setEnabled(false);
        jtusuario.setEditable(false);
        jtusuario.setEnabled(false);
        jpsenha.setEditable(false);
        jpsenha.setEnabled(false);
        jpconfSenha.setEditable(false);
        jpconfSenha.setEnabled(false);
        jbeditar.setEnabled(true);
        jbsalvar.setEnabled(false);
        jbcancelar.setEnabled(false);
        jbvoltar.setEnabled(true);
    }//GEN-LAST:event_jbeditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeditar;
    private javax.swing.JButton jbpesquisar;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JButton jbvoltar;
    private javax.swing.JComboBox jcUF;
    private javax.swing.JComboBox jcsetor;
    private javax.swing.JComboBox jcsexo;
    private javax.swing.JPasswordField jpconfSenha;
    private javax.swing.JPasswordField jpsenha;
    private javax.swing.JTextField jtCEP;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtRG;
    private javax.swing.JTextField jtbairro;
    private javax.swing.JTextField jtcidade;
    private javax.swing.JTextField jtcontato;
    private javax.swing.JTextField jtdataCadastro;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtendereco;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtregistro;
    private javax.swing.JTextField jtusuario;
    // End of variables declaration//GEN-END:variables
private boolean validarCampos() {
        if (jtdataCadastro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a data de cadastro");
            jtdataCadastro.requestFocus();
            return false;
        }
        if (jtmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a Matricula");
            jtmatricula.requestFocus();
            return false;
        }
        if (jtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o nome");
            jtnome.requestFocus();
            return false;
        }
        if (jcsexo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione o sexo");
            jcsexo.requestFocus();
            return false;
        }
        if (jcsetor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione o setor");
            jcsetor.requestFocus();
            return false;
        }
        if (jtendereco.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o endereço");
            jtendereco.requestFocus();
            return false;
        }

        if (jcUF.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione o UF");
            jcUF.requestFocus();
            return false;
        }

        if (jtbairro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o bairro");
            jtbairro.requestFocus();
            return false;
        }
        if (jtcidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a cidade");
            jtcidade.requestFocus();
            return false;
        }
        if (jtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o CEP");
            jtCEP.requestFocus();
            return false;
        }
        if (jtemail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o email");
            jtemail.requestFocus();
            return false;
        }

        if (jtCPF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o CPF");
            jtCPF.requestFocus();
            return false;
        }
        if (jtcontato.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o cotato");
            jtcontato.requestFocus();
            return false;
        }

        if (jtRG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o RG");
            jtRG.requestFocus();
            return false;
        }
        if (jtusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o usuário");
            jtusuario.requestFocus();
            return false;
        }
        if (jpsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a senha");
            jpsenha.requestFocus();
            return false;
        }
        if (jpconfSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a confirmação de senha");
            jpconfSenha.requestFocus();
            return false;
        }

        return true;
    }

    private boolean preencherObject() throws Exception {
        f = new Funcionarios();
        f.setDataCadastro(jtdataCadastro.getText());
        f.setMatricula(jtmatricula.getText());
        f.setNome(jtnome.getText());
        f.setSexo(jcsexo.getSelectedIndex());
        f.setSetor(jcsetor.getSelectedIndex());
        f.setEndereco(jtendereco.getText());
        f.setUF(jcUF.getSelectedIndex());
        f.setBairro(jtbairro.getText());
        f.setCidade(jtcidade.getText());
        f.setCEP(jtCEP.getText());
        f.setEmail(jtemail.getText());
        f.setCPF(jtCPF.getText());
        f.setContato(jtcontato.getText());
        f.setRG(jtRG.getText());
        f.setLogin(jtusuario.getText());
        f.setSenha(jpsenha.getText());
        f.setConfSenha(jpconfSenha.getText());

        return true;
    }

    private void limparCampos() {
        jtdataCadastro.setText("");
        jtmatricula.setText("");
        jtnome.setText("");
        jcsexo.setSelectedIndex(0);
        jcsetor.setSelectedIndex(0);
        jtendereco.setText("");
        jcUF.setSelectedIndex(0);
        jtbairro.setText("");
        jtcidade.setText("");
        jtCEP.setText("");
        jtemail.setText("");
        jtCPF.setText("");
        jtcontato.setText("");
        jtRG.setText("");
        jtusuario.setText("");
        jpsenha.setText("");
        jpconfSenha.setText("");

    }

}
